.TH VINAGRE "1" "January 12th 2008" "User Commands"
.SH NAME
vinagre \- a VNC client for the GNOME Desktop
.SH SYNOPSYS
.SS "Usage:"
.IP
vinagre [OPTION...] [server:port] \- VNC Client for GNOME
.SS "Help Options:"
.TP
\-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-f\fR, \fB\-\-file\fR=\fIfilename\fR
Opens a .vnc file
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.PP
Run 'vinagre \fB\-\-help\fR' to see a full list of available command line options

.SH AUTHOR
Vinagre was written by Jonh Wendell <wendell@bani.com.br>
.TP
This manual page was written by Emilio Pozuelo Monfort <pochu@ubuntu.com>.

